ALTER TYPE "DeliveryOtpPurpose" ADD VALUE IF NOT EXISTS 'BUYER_LOGIN';
ALTER TYPE "DeliveryOtpPurpose" ADD VALUE IF NOT EXISTS 'ADMIN_LOGIN';
ALTER TYPE "DeliveryOtpPurpose" ADD VALUE IF NOT EXISTS 'SELLER_LOGIN';
