import { Button, ScrollView, Text, View } from '@tarojs/components';
import Taro, { useDidShow, useRouter } from '@tarojs/taro';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CatalogFeedback } from '@/components/catalog-feedback';
import { useAuthStore } from '@/store/auth';
import { InvoiceAuthGate } from '../_components/auth-gate';
import { openInvoicePdf } from '../pdf';
import { MiniInvoiceRepo } from '../repo';
import { formatTime, INVOICE_STATUS_LABELS } from '../utils';
import '../_components/invoice-shared.scss';
import './index.scss';

function Row({ label, value, copy }: { label: string; value: string; copy?: boolean }) { return <View className='invoice-detail-row'><Text>{label}</Text><Text onClick={() => { if (copy) void Taro.setClipboardData({ data: value }); }}>{value}{copy ? '  复制' : ''}</Text></View>; }

export default function InvoiceDetailPage() {
  const router = useRouter(); const id = typeof router.params.id === 'string' ? router.params.id : ''; const loggedIn = useAuthStore((state) => Boolean(state.accessToken)); const queryClient = useQueryClient();
  const query = useQuery({ queryKey: ['invoice', id], queryFn: () => MiniInvoiceRepo.getById(id), enabled: loggedIn && Boolean(id), refetchInterval: (q) => q.state.data?.ok && q.state.data.data.status === 'REQUESTED' ? 15_000 : false });
  useDidShow(() => { if (id && useAuthStore.getState().accessToken) void query.refetch(); }); const invoice = query.data?.ok ? query.data.data : undefined;
  const cancelMutation = useMutation({ mutationFn: () => MiniInvoiceRepo.cancel(id), onSuccess: async (result) => { if (!result.ok) { Taro.showToast({ title: result.error.displayMessage || '取消失败', icon: 'none' }); return; } await Promise.all([queryClient.invalidateQueries({ queryKey: ['invoice', id] }), queryClient.invalidateQueries({ queryKey: ['invoices'] }), queryClient.invalidateQueries({ queryKey: ['orders'] })]); Taro.showToast({ title: '已取消开票申请', icon: 'success' }); } });
  const cancel = async () => { const modal = await Taro.showModal({ title: '取消开票申请', content: '开票服务商已受理的申请可能无法取消，取消结果会在本页更新。', confirmColor: '#A04B42' }); if (modal.confirm) cancelMutation.mutate(); };
  const openPdf = async () => { try { await openInvoicePdf(invoice?.pdfUrl); } catch (error) { Taro.showToast({ title: error instanceof Error ? error.message : '无法打开发票', icon: 'none' }); } };
  const returnUrl = `/packages/invoices/invoice-detail/index?id=${encodeURIComponent(id)}`;
  return <InvoiceAuthGate returnUrl={returnUrl}><View className='invoice-detail-page'>{!id ? <CatalogFeedback kind='error' title='发票参数缺失' description='请从发票列表重新进入' /> : query.isLoading ? <CatalogFeedback kind='loading' /> : !invoice ? <CatalogFeedback kind='error' title='发票详情加载失败' description={query.data && !query.data.ok ? query.data.error.displayMessage : '请稍后重试'} onRetry={() => query.refetch()} /> : <ScrollView className='invoice-detail-scroll' scrollY enhanced refresherEnabled refresherTriggered={query.isRefetching} onRefresherRefresh={() => query.refetch()}><View className='invoice-detail-content'><View className='invoice-detail-receipt aim-card'><View className='invoice-detail-receipt__head'><Text>电子发票</Text><Text className={`invoice-status invoice-status--${invoice.status.toLowerCase()}`}>{INVOICE_STATUS_LABELS[invoice.status]}</Text></View><View className='invoice-detail-receipt__tear' /><Text className='invoice-detail-receipt__title'>{invoice.profileSnapshot.title}</Text>{invoice.invoiceNo ? <Text className='invoice-detail-receipt__no'>NO. {invoice.invoiceNo}</Text> : null}<Text className='invoice-detail-receipt__hint'>{invoice.status === 'REQUESTED' ? '系统正在处理，状态会自动刷新' : invoice.status === 'FAILED' ? invoice.failReason || '开票失败，可联系客服核实' : invoice.status === 'ISSUED' ? '发票已开具，可下载 PDF' : '该开票申请已取消'}</Text></View>
    <View className='invoice-detail-card aim-card'><Text className='invoice-detail-card__title'>抬头快照</Text><Row label='类型' value={invoice.profileSnapshot.type === 'COMPANY' ? '企业' : '个人'} /><Row label='抬头' value={invoice.profileSnapshot.title} />{invoice.profileSnapshot.taxNo ? <Row label='税号' value={invoice.profileSnapshot.taxNo} copy /> : null}{invoice.profileSnapshot.email ? <Row label='邮箱' value={invoice.profileSnapshot.email} /> : null}{invoice.profileSnapshot.phone ? <Row label='手机' value={invoice.profileSnapshot.phone} /> : null}{invoice.profileSnapshot.bankInfo?.bankName ? <Row label='开户行' value={invoice.profileSnapshot.bankInfo.bankName} /> : null}{invoice.profileSnapshot.bankInfo?.accountNo ? <Row label='银行账号' value={invoice.profileSnapshot.bankInfo.accountNo} copy /> : null}{invoice.profileSnapshot.address ? <Row label='注册地址' value={invoice.profileSnapshot.address} /> : null}</View>
    <View className='invoice-detail-card aim-card'><Text className='invoice-detail-card__title'>关联信息</Text><Row label='订单号' value={invoice.orderId} copy />{invoice.order?.totalAmount != null ? <Row label='订单金额' value={`¥${Number(invoice.order.totalAmount).toFixed(2)}`} /> : null}<Row label='申请时间' value={formatTime(invoice.requestedAt || invoice.createdAt)} />{invoice.issuedAt ? <Row label='开票时间' value={formatTime(invoice.issuedAt)} /> : null}</View>
    {invoice.statusHistory?.length ? <View className='invoice-detail-card aim-card'><Text className='invoice-detail-card__title'>状态记录</Text>{[...invoice.statusHistory].reverse().map((item) => <View className='invoice-detail-history' key={item.id}><View /><View><Text>{INVOICE_STATUS_LABELS[item.toStatus]}</Text>{item.reason ? <Text className='invoice-detail-history__meta'>{item.reason}</Text> : null}<Text className='invoice-detail-history__meta'>{formatTime(item.createdAt)}</Text></View></View>)}</View> : null}
    {invoice.status === 'ISSUED' && invoice.pdfUrl ? <Button className='invoice-detail-primary' onClick={openPdf}>查看电子发票 PDF</Button> : null}{invoice.status === 'REQUESTED' ? <Button className='invoice-detail-danger' disabled={cancelMutation.isPending} onClick={cancel}>{cancelMutation.isPending ? '取消中...' : '取消开票申请'}</Button> : null}</View></ScrollView>}</View></InvoiceAuthGate>;
}
